version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/test-ci-code
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9e:57:4a:dd:7e:2e:7d:36:96:2d:e5:94:5a:83:9a:90"
      - checkout
      - run:
          name: install
          command: "npm install"
      - run:
          name: git config
          command: |
            git config user.email "ci-build@lemoncode.net"
            git config user.name "ci-build"
      - run:
          name: deploy
          command: "npm run deploy"
